// Frame rate at home, on a section page at rest, and during a turn: node scripts/fps.mjs
import { chromium } from 'playwright'
const browser = await chromium.launch({ channel: 'chromium', env: { ...process.env, __NV_PRIME_RENDER_OFFLOAD: '1', __GLX_VENDOR_LIBRARY_NAME: 'nvidia' }, args: ['--ignore-gpu-blocklist', '--use-gl=angle', '--use-angle=gl'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.error('pageerror', e.message))
await page.goto('http://localhost:5173/')
await page.waitForFunction(() => window.__aarNav && document.querySelector('canvas')?.width > 300)
await page.waitForTimeout(2500)
const fps = (ms) => page.evaluate((ms) => new Promise((res) => { let n = 0; const t0 = performance.now(); const tick = () => { n++; if (performance.now() - t0 < ms) requestAnimationFrame(tick); else res(Math.round((n * 1000) / (performance.now() - t0))) }; requestAnimationFrame(tick) }), ms)
console.log('home', await fps(3000), 'fps')
await page.evaluate(() => { window.__aarNav.go(1) })
await page.waitForTimeout(4000)
await page.waitForFunction(() => !window.__aarNav.busy(), null, { timeout: 20000 })
console.log('page at rest', await fps(3000), 'fps')
await page.evaluate(() => { window.__aarNav.next() })
console.log('during next', await fps(2000), 'fps')
await page.waitForFunction(() => !window.__aarNav.busy(), null, { timeout: 20000 })
await browser.close()
