// Land on Creatives, go to Web Design, hover the picture and screenshot; report the anchor's box and its href
import { chromium } from 'playwright'
const browser = await chromium.launch({ channel: 'chromium', env: { ...process.env, __NV_PRIME_RENDER_OFFLOAD: '1', __GLX_VENDOR_LIBRARY_NAME: 'nvidia' }, args: ['--ignore-gpu-blocklist', '--use-gl=angle', '--use-angle=gl'] })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
page.on('pageerror', (e) => console.error('pageerror', e.message))
await page.goto('http://localhost:5173/')
await page.waitForFunction(() => window.__aarNav && document.querySelector('canvas')?.width > 300)
await page.waitForTimeout(2500)
await page.evaluate(() => { window.__aarNav.go(3, 1) })
await page.waitForTimeout(4000)
await page.waitForFunction(() => !window.__aarNav.busy(), null, { timeout: 20000 })
await page.waitForTimeout(800)
const hot = page.locator('.page-hot').first()
const box = await hot.boundingBox()
console.log('anchor', JSON.stringify(box), await hot.getAttribute('href'))
await hot.hover()
await page.waitForTimeout(300)
await page.screenshot({ path: 'shots/hot-webdesign.png' })
await browser.close()
console.log('shots/hot-webdesign.png')
